cmf:
  name: cmf
  version: 1.0.0
  copyRighYear: 2018
  #??????��??
  profile: D:/profile/
  #mybatis
mybatis:
  # ?????????????
   typeAliasesPackage: zjnu.cmf.project
   # ????mapper????�k??????��?mapper.xml??????
   mapperLocations: classpath:mybatis/**/*Mapper.xml
   # ???????????????
   configLocation: classpath:mybatis-config.xml
# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#shiro
shiro:
  user:
      # ??????
      loginUrl: /login
      # ???????????
      unauthorizedUrl: /unauth
      # ??????
      indexUrl: /index
      # ???????
      captchaEbabled: true
      # ????????? math ??????? char ???
      captchaType: math
  cookie:
      # ????Cookie?????? ???????????????????
      domain:
      # ????cookie????��????��??
      path: /
      # ????HttpOnly????
      httpOnly: true
      # ????Cookie?????????????��
      maxAge: 30
  session:
      # Session?????????30?????
      expireTime: 30
      # ???session????????????????1?????
      dbSyncPeriod: 1
      # ?????��?????session????��?????????10????
      validationInterval: 10
#??????????spring:#
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry_20180801?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 1234
    # ???????��????��?????
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # ????????????????????
    maxWait: 60000
    # ???��????��??????��??????????????????????��?????
    timeBetweenEvictionRunsMillis: 60000
    # ??????????????????��??????????��?????
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # ??PSCache??????????????????PSCache???��
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # ???��??????????filters????????????sql???????'wall'????????
    filters: stat,wall,slf4j
    # ???connectProperties????????mergeSql???????SQL???
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # ??????DruidDataSource????????
    #useGlobalDataSourceStat: true
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
  #???????????��??
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#????????
gen:
  #????
  author: cmf
  # ????????��?? module ???????????????? ?? system monitor tool
  packageName: zjnu.cmf.project.system
  # ?????????????????true
  autoRemovePre: true
  # ????(???????????????)
  tablePrefix: sys_





